{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  annotations:
    {{- if eq .Values.cloudProvider "aws" }}
      {{- range $key, $value := .Values.ingress.aws.annotations }}
    {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- else if eq .Values.cloudProvider "gcp" }}
      {{- range $key, $value := .Values.ingress.gcp.annotations }}
    {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- else if eq .Values.cloudProvider "azure" }}
      {{- range $key, $value := .Values.ingress.azure.annotations }}
    {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
spec:
  ingressClassName: {{- if eq .Values.cloudProvider "aws" }}{{ .Values.ingress.aws.ingressClassName }}{{- else if eq .Values.cloudProvider "gcp" }}{{ .Values.ingress.gcp.ingressClassName }}{{- else if eq .Values.cloudProvider "azure" }}{{ .Values.ingress.azure.ingressClassName }}{{- end }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.appName }}-service
                port:
                  number: {{ .Values.service.port }}
{{- end }}